# Generated by Django 2.0.1 on 2018-01-07 06:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', encrypted_model_fields.fields.EncryptedTextField(verbose_name='Encrypted Message')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('expiration_timestamp', models.DateTimeField(default=datetime.datetime(2018, 1, 14, 6, 29, 45, 138868, tzinfo=utc), verbose_name='Expiration Date')),
            ],
            options={
                'verbose_name_plural': 'Secrets',
                'db_table': 'secrets',
            },
        ),
    ]
